### ISSUE TITLE
flax dataclass instead of chex

### ISSUE THREAD

**Issue by Howuhh** [joeryjoery/jit_env#24]
Is there any reason to prefer chex dataclasses? One issue I see is that there is no option for fields to be registered as non pytree nodes (see https://flax.readthedocs.io/en/latest/api_reference/flax.struct.html). This can be useful for planned options. For example, with such values we can perform operations that expect real values and not tracers (if, while, slicing, etc). While we can not vmap on them, we still can change them between resets. With chex dataclasses it is not possible is seems.

**Comment by joeryjoery** [comment]
I think the only place where a `dataclass` is used in the entire repo is for `TimeStep`. I wanted to keep this at `NamedTuple` actually from dm_env but this object is not compatible with dataclass transformations like `replace`. 

I prefer keeping `chex.dataclass` for `TimeStep` as it reduces the requirement list as `chex` is already included for the tests. For Environment implementations you often don't even have to call `TimeStep` directly as you can do this with the helper methods `restart`, `transition`, `termination`, `truncation`.

You're always free to use `flax` based (or other) dataclasses for e..g, the State or Action or Observation objects. It is also not intended to modify `TimeStep` in any way as it would violate the interface.
